enum TechProcessActionTypes {
    TECHPROCESS_INIT,
    TECHPROCESS_LOAD_EDIT,
    TECHPROCESS_CREATE,
    TECHPROCESS_DELETE,
    TECHPROCESS_UPDATE,
    TECHPROCESS_PAGE_CHANGE,
    TECHPROCESSES_PER_PAGE_CHANGE,
    TECHPROCESS_SEARCH_TEXT_CHANGE
}

export default TechProcessActionTypes