enum TechOperationActionTypes {
    TECHOPERATION_INIT,
    TECHOPERATION_LOAD_EDIT,
    TECHOPERATION_CREATE,
    TECHOPERATION_DELETE,
    TECHOPERATION_UPDATE,
    TECHOPERATION_PAGE_CHANGE,
    TECHOPERATIONS_PER_PAGE_CHANGE,
    TECHOPERATION_SEARCH_TEXT_CHANGE
}

export default TechOperationActionTypes