enum TechStepActionTypes {
    TECHSTEP_INIT,
    TECHSTEP_LOAD_EDIT,
    TECHSTEP_CREATE,
    TECHSTEP_DELETE,
    TECHSTEP_UPDATE,
    TECHSTEP_PAGE_CHANGE,
    TECHSTEPS_PER_PAGE_CHANGE,
    TECHSTEP_SEARCH_TEXT_CHANGE
}

export default TechStepActionTypes