enum ToolActionTypes {
    TOOL_INIT,
    TOOL_LOAD,
    TOOL_LOAD_PENDING,
    TOOL_LOAD_SUCCEED,
    TOOL_LOAD_FAILED,
    TOOL_UPDATE_TOOL_LIST,
    TOOL_SAVE_PENDING,
    TOOL_SAVE_SUCCEED,
    TOOL_SAVE_FAILED,
    TOOL_DELETE_PENDING,
    TOOL_DELETE_SUCCEED,
    TOOL_DELETE_FAILED,
    TOOL_SHOW_DELETE_CONFIRMATION,
    TOOL_CLOSE_DELETE_CONFIRMATION,
    TOOL_REDO,
    TOOL_UNDO,
    TOOL_CHANGE,
    TOOL_LOAD_EDIT,
    TOOL_CREATE,
    TOOL_DELETE,
    TOOL_UPDATE,
    TOOL_PAGE_CHANGE,
    TOOLS_PER_PAGE_CHANGE,
    TOOL_SEARCH_TEXT_CHANGE
}

export default ToolActionTypes