enum ToolActionTypes {
    TOOL_INIT,
    TOOL_LOAD,
    TOOL_UPDATE_TOOL_LIST,
    TOOL_SHOW_DELETE_CONFIRMATION,
    TOOL_CLOSE_DELETE_CONFIRMATION,
    TOOL_LOAD_EDIT,
    TOOL_CREATE,
    TOOL_DELETE,
    TOOL_UPDATE,
    TOOL_PAGE_CHANGE,
    TOOLS_PER_PAGE_CHANGE,
    TOOL_SEARCH_TEXT_CHANGE
}

export default ToolActionTypes